name: $(Year:yyyy).$(Month:MM)$(DayOfMonth:dd)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - sitecore/foundation/README.md
    include:
    - sitecore/foundation/*

pool:
  vmImage: 'windows-2019'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'ICF Next'
    repository: 'sitecore/foundation'
    command: 'buildAndPush'
    buildContext: "sitecore/foundation"
    Dockerfile: 'sitecore/foundation/Dockerfile'
    tags: |
      latest
      $(Build.BuildNumber)-windowsservercore-ltsc2019
