trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - xconnect/marketing-automation/engine/README.md
    include:
    - xconnect/marketing-automation/engine/*

pool:
  vmImage: 'windows-2019'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'ICF Next'
    repository: 'sitecore/xconnect/marketing-automation/engine'
    command: 'buildAndPush'
    buildContext: "xconnect/marketing-automation/engine"
    Dockerfile: 'xconnect/marketing-automation/engine/Dockerfile'
    tags: |
      latest
      9.1.1-windowsservercore-ltsc2019
      $(Build.BuildNumber)-windowsservercore-ltsc2019
