trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - solr/sitecore-solr/README.md
    include:
    - solr/sitecore-solr/*

pool:
  vmImage: 'windows-2019'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'ICF Next'
    repository: 'sitecore/solr-win'
    command: 'buildAndPush'
    buildContext: "solr/sitecore-solr"
    Dockerfile: 'solr/sitecore-solr/Dockerfile'
    tags: |
      latest
      $(Build.BuildNumber)-windowsservercore-ltsc2019
