# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Year:yyyy).$(Month:MM)$(DayOfMonth:dd)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - sitecore/util/*

pool:
  vmImage: 'windows-2019'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'ICF Next'
    repository: 'sitecore/util'
    command: 'buildAndPush'
    buildContext: "sitecore/util"
    Dockerfile: 'sitecore/util/Dockerfile'
    tags: |
      latest
      $(Build.BuildNumber)-windowsservercore-ltsc2019
