trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - sitecore/content-management/foundation/README.md
    include:
    - sitecore/content-management/foundation/*

pool:
  vmImage: 'windows-2019'

steps:

- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)'
    vstsFeed: 'sitecore'
    vstsFeedPackage: 'sitecore-xp'
    vstsPackageVersion: 9.1.1

- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)/sitecore/content-management/foundation'
    vstsFeed: 'sitecore'
    vstsFeedPackage: 'license'
    vstsPackageVersion: 1.0.0

- task: CmdLine@2
  inputs:
    script: 'copy "Sitecore 9.1.1 rev. 002459 (Cloud)_cm.scwdp.zip" $(System.DefaultWorkingDirectory)\sitecore\content-management\foundation\package.scwdp.zip'

- task: Docker@2
  inputs:
    containerRegistry: 'ICF Next'
    repository: 'sitecore/content-management/foundation'
    command: 'buildAndPush'
    buildContext: "sitecore/content-management/foundation"
    Dockerfile: 'sitecore/content-management/foundation/Dockerfile'
    tags: |
      latest
      9.1.1-windowsservercore-ltsc2019
      $(Build.BuildNumber)-windowsservercore-ltsc2019
